#!/bin/csh
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# Setet up idl environment variables for ezcaIDL
#

set HOST_ARCH = `/usr/local/epics/startup/HostArch`
if $HOST_ARCH == "" then 
	set HOST_ARCH=solaris
endif
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = $EPICS_EXTENSIONS/bin/$HOST_ARCH
set PVT_LIB = $EPICS_EXTENSIONS/lib/$HOST_ARCH

# set EZCA_IDL_SHARE & IDL_STARTUP

        setenv  EZCA_IDL_SHARE $PVT_LIB/libezcaIDL.so
        setenv  IDL_STARTUP $PVT_LOC/ezcaidl_startup.pro 

# if private version exist override by them

if ${?EPICS_EXT_PVT} == 1 then 
	 set PVT_LOC = $EPICS_EXT_PVT/bin/$HOST_ARCH
	 set PVT_LIB = $EPICS_EXT_PVT/lib/$HOST_ARCH
else if ${?EPICS_EXTENSIONS_PVT} == 1 then 
	 set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
	 set PVT_LIB = $EPICS_EXTENSIONS_PVT/lib/$HOST_ARCH
endif 

if ( ${?EPICS_EXT_PVT} | ${?EPICS_EXTENSIONS_PVT} ) then
	setenv LD_LIBRARY_PATH $PVT_LIB':'$LD_LIBRARY_PATH
#	setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${PVT_LIB}
	if  -e $PVT_LIB/libezcaIDL.so  then
        setenv EZCA_IDL_SHARE $PVT_LIB/libezcaIDL.so
	endif
	if  -e $PVT_LOC/ezcaidl_startup.pro  then
        setenv IDL_STARTUP $PVT_LOC/ezcaidl_startup.pro 
	endif
endif

if -e libezcaIDL.so  then
        setenv  EZCA_IDL_SHARE libezcaIDL.so
endif
if -e ezcaidl_startup.pro  then
        setenv  IDL_STARTUP ezcaidl_startup.pro 
endif

# release 5.0
#source /usr/local/rsi/idl_5.2/bin/idl_setup
setenv IDL_DEVICE X

#setenv IDL_PATH  ${PVT_LOC}:${IDL_PATH}
echo LD_LIBRARY_PATH $LD_LIBRARY_PATH
echo EZCA_IDL_SHARE $EZCA_IDL_SHARE
echo IDL_STARTUP $IDL_STARTUP
exit

