#!/bin/csh -f
set HOST_ARCH = `/usr/local/epics/startup/HostArch`
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = $EPICS_EXTENSIONS/bin/$HOST_ARCH

if ${?EPICS_EXTENSIONS_PVT} == 1 then 
	set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif

setenv IDL_DEVICE X

source /usr/local/rsi/idl_5/bin/idl_setup

setenv IDL_STARTUP $PVT_LOC/viewer_startup.pro

echo ".run ez_fit" >! go_ezfit
echo "ez_fit" >>! go_ezfit
idl go_ezfit
rm go_ezfit
