#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
if ${?EPICS_EXTENSIONS} then 
	set LOC_PVT=/usr/local/epics/extensions/bin/$HOST_ARCH
endif
set LOC_PVT=$EPICS_EXTENSIONS/bin/$HOST_ARCH
if ${?EPICS_EXTENSIONS_PVT} then 
	set LOC_PVT=$EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif
source $LOC_PVT/idluserdir_setup
cd $IDL_USERDIR

setenv IDL_STARTUP $LOC_PVT/viewer_startup.pro

echo ".run hdfb" >! go_hdfb
echo "hdfb" >>! go_hdfb
idl go_hdfb
rm go_hdfb
