#!/bin/csh -f
if ${?EPICS_EXTENSIONS} then 
	set LOC_PVT=/usr/local/epics/extensions/bin/$HOST_ARCH
endif
set LOC_PVT=$EPICS_EXTENSIONS/bin/$HOST_ARCH
if ${?EPICS_EXTENSIONS_PVT} then 
	set LOC_PVT=$EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif
source $LOC_PVT/idluserdir_setup
cd $IDL_USERDIR

setenv IDL_STARTUP $LOC_PVT/viewer_startup.pro

echo ".run hdfb" >! go_hdfb
echo "hdfb" >>! go_hdfb
idl go_hdfb
rm go_hdfb
