#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
source $EPICS_EXTENSIONS/bin/solaris-sparc/idluserdir_setup

echo "@os.init" >! go_viewer
echo ".run PS_open" >>! go_viewer
echo ".run image.pro" >>! go_viewer
echo "img" >>! go_viewer
idl go_viewer
rm go_viewer
