#!/bin/csh -f
set HOST_ARCH = `/usr/local/epics/startup/HostArch`
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = $EPICS_EXTENSIONS/bin/$HOST_ARCH

if ${?EPICS_EXTENSIONS_PVT} == 1 then 
	set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif

setenv IDL_DEVICE X

# source /usr/local/rsi/idl_5.4/bin/idl_setup
source $PVT_LOC/idluserdir_setup
cd $IDL_USERDIR

setenv IDL_STARTUP $PVT_LOC/viewer_startup.pro

echo "@os.init" >! go_viewer
echo ".run PS_open" >>! go_viewer
echo ".run image.pro" >>! go_viewer
echo "img" >>! go_viewer
idl go_viewer
rm go_viewer
