
EPICS = ../../../..
include $(EPICS)/config/CONFIG_EXTENSIONS

DOCS = catcher.README catcher.html  catcher_help.txt view2d_help.txt
SCRIPTS = setup_ezcaIDL ezcaidl_startup.pro \
	os.init PS_open.pro u_read.pro plot1d.pro \
	catcher_v1.pro catcher_v1.init catcher toImage.pro\
	catcher.exe2 catcher.exe2.idl5 \
	viewer dcviewer.pro viewer_startup.pro \
	view1d.pro view1d.init view1d_overlay.pro \
	view2d.pro view2d.init makeIDLRef.pro 

include $(EPICS)/config/RULES.Unix

