#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
source $EPICS_EXTENSIONS/bin/solaris-sparc/idluserdir_setup

set PRM=""
if $1 != "" then 
	set PRM=",file='$1'"
endif

echo ".run ez_fit" >! go_viewer
echo ".run nexus_scan.pro" >>! go_viewer
echo "nexus_scan $PRM" >>! go_viewer
if `isainfo -b` == 64 then
	source /usr/local/rsi/idl_5.5/bin/idl_setup
else
	source /usr/local/rsi/idl_5.3/bin/idl_setup
endif
	idl go_viewer
rm go_viewer

