#!/bin/csh -f
set HOST_ARCH = `/usr/local/epics/startup/HostArch`
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = $EPICS_EXTENSIONS/bin/$HOST_ARCH

if ${?EPICS_EXTENSIONS_PVT} == 1 then 
        set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif

setenv IDL_DEVICE X

#source /usr/local/rsi/idl_5.1/bin/idl_setup
source $PVT_LOC/idluserdir_setup
cd $IDL_USERDIR

setenv IDL_STARTUP $PVT_LOC/viewer_startup.pro

set runfile=""
if "$1" != "" then
	set runfile = ",file='$1'"
endif
echo ".run ez_fit" >! go_viewer
echo ".run pick3d" >>! go_viewer
echo "pick3d"$runfile   >>! go_viewer
;idl go_viewer
;rm go_viewer

