#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
source $EPICS_EXTENSIONS/bin/solaris-sparc/idluserdir_setup

set runfile=""
if "$1" != "" then
	set runfile = ",file='$1'"
endif
echo ".run ez_fit" >! go_viewer
echo ".run pick3d" >>! go_viewer
echo "pick3d"$runfile   >>! go_viewer
;idl go_viewer
;rm go_viewer

