#!/bin/csh -f
set HOST_ARCH = `/usr/local/epics/startup/HostArch`
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = $EPICS_EXTENSIONS/bin/$HOST_ARCH

if ${?EPICS_EXTENSIONS_PVT} == 1 then 
	set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif

setenv IDL_DEVICE X

#source /usr/local/rsi/idl_5.1/bin/idl_setup

setenv IDL_STARTUP $PVT_LOC/viewer_startup.pro

echo ".run ez_fit" >! go_viewer
echo ".run read_scan.pro.R2" >>! go_viewer
echo ".run readScan.pro.R2" >>! go_viewer
echo ".run scanSee__define.pro.R2" >>! go_viewer
echo ".run scanSee.pro" >>! go_viewer
echo "scanSee" >>! go_viewer
idl go_viewer
rm go_viewer

