#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
source $EPICS_EXTENSIONS/bin/$EPICS_HOST_ARCH/idluserdir_setup

set PRM=""
if $1 != "" then 
	set PRM=",filename='$1'"
endif

echo ".run ez_fit" >! go_viewer
echo ".run readScan.pro" >>! go_viewer
echo ".run read_scan.pro.R2" >>! go_viewer
echo ".run scanSee__define.pro" >>! go_viewer
echo ".run scanSee.pro" >>! go_viewer
echo "scanSee $PRM" >>! go_viewer
idl go_viewer
rm go_viewer

