#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
set HOST_ARCH = `/usr/local/epics/startup/HostArch`
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = $EPICS_EXTENSIONS/bin/$HOST_ARCH

if ${?EPICS_EXTENSIONS_PVT} == 1 then 
	set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif
source $PVT_LOC/idluserdir_setup
cd $IDL_USERDIR

setenv IDL_DEVICE X

#source /usr/local/rsi/idl_5.1/bin/idl_setup

setenv IDL_STARTUP $PVT_LOC/viewer_startup.pro

echo ".run ez_fit" >! go_viewer
echo ".run scanSee__define" >>! go_viewer
echo ".run scansee_browser" >>! go_viewer
echo "scansee_browser" >>! go_viewer
if `isainfo -b` == 64 then
        source /usr/local/rsi/idl_5.5/bin/idl_setup
        idl -32 go_viewer
else
        source /usr/local/rsi/idl_5.3/bin/idl_setup
        idl go_viewer
endif
rm go_viewer

