#!/bin/csh -f
set HOST_ARCH = `/usr/local/epics/startup/HostArch`
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = $EPICS_EXTENSIONS/bin/$HOST_ARCH

if ${?EPICS_EXTENSIONS_PVT} == 1 then 
	set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif

#source /usr/local/rsi/idl_5.1/bin/idl_setup

setenv IDL_DEVICE X

if ${?EPICS_EXTENSIONS_PVT} == 1 then
        source $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH/ezcaidl_setup
else
        source $EPICS_EXTENSIONS/bin/$HOST_ARCH/ezcaidl_setup
endif

set xdr = "DC"

echo ".run read_scan.pro.R2" >! go_viewer
echo ".run readScan.pro.R2" >>! go_viewer
echo ".run DC.pro.R2.0" >>! go_viewer
echo ".run vw2d.pro.R2.0" >>! go_viewer
echo "$xdr" >>! go_viewer
idl go_viewer
rm go_viewer
