#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
source $EPICS_EXTENSIONS/bin/solaris-sparc/idluserdir_setup

echo ".run ez_fit" >! go_viewer
echo ".run scanSee__define" >>! go_viewer
echo ".run scansee_browser" >>! go_viewer
echo "scansee_browser" >>! go_viewer
#if `isainfo -b` == 64 then
#        source /usr/local/rsi/idl_5.5/bin/idl_setup
#        idl -32 go_viewer
#else
#        source /usr/local/rsi/idl_5.3/bin/idl_setup
        idl go_viewer
#endif
rm go_viewer

