#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
source $EPICS_EXTENSIONS/bin/solaris-sparc/idluserdir_setup
source $PVT_LOC/ezcaidl_setup

if $HOST_ARCH == "solaris-sparc" then 
	set exe = "-rt=$PVT_LOC/../../idllib/scanSee.exe2.idl55"
	else
	set exe = "-rt=$PVT_LOC/scanSee.exe2.idl53"
endif
	if -e scanSee.exe2.idl53 then
	set exe = "scanSee.exe2.idl53"
	endif

if ( "$1" == "" ) then
#setenv IDL_NCOLORS 32
	source /usr/local/rsi/idl_5.5/bin/idl_setup
	idl -32 $exe
exit
endif

set xdr = "DC"
while ( "$1" !=  "" )
if ( "$1" == "-A" | "$1" == "-a" | "$1" == "-Auto" ) then
        set xdr = 'DC,/autoscan'
        shift
endif

echo ".run readScan.pro" >! go_viewer
echo ".run panimage.pro" >>! go_viewer
echo ".run vw2d.pro" >>! go_viewer
echo ".run DC.pro" >>! go_viewer
echo ".run user_scan.pro" >>! go_viewer
echo "$xdr" >>! go_viewer
cat go_viewer
#if `isainfo -b` == 64 then
	source /usr/local/rsi/idl_5.5/bin/idl_setup
	idl -32 go_viewer
#else
#	source /usr/local/rsi/idl_5.3/bin/idl_setup
#	idl go_viewer
#endif
rm go_viewer
