#!/bin/csh
#
# Setet up idl environment variables for ezcaIDL
#

set HOST_ARCH = `/usr/local/epics/startup/HostArch`
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = /usr/local/epics/extensions/bin/$HOST_ARCH

        setenv  EZCA_IDL_SHARE $PVT_LOC/ezcaIDL.so
        setenv  EZCA_WAVE_SHARE $PVT_LOC/ezcaWave.so
        setenv  IDL_STARTUP $PVT_LOC/ezcaidl_startup.pro 

# set EZCA_IDL_SHARE
# set IDL_STARTUP

if ${?EPICS_EXT_PVT} == 1 then 
	 set PVT_LOC = $EPICS_EXT_PVT/bin/$HOST_ARCH
else if ${?EPICS_EXTENSIONS_PVT} == 1 then 
	 set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif 

if -e ezcaIDL.so  then
        setenv  EZCA_IDL_SHARE ezcaIDL.so
        setenv  EZCA_WAVE_SHARE ezcaWave.so
else if ${?EPICS_EXT_PVT} == 1 or ${?EPICS_EXTENSIONS_PVT} == 1 then
	if  -e $PVT_LOC/ezcaIDL.so  then
        setenv  EZCA_IDL_SHARE $PVT_LOC/ezcaIDL.so
        setenv  EZCA_WAVE_SHARE $PVT_LOC/ezcaWave.so
        setenv  IDL_STARTUP $PVT_LOC/ezcaidl_startup.pro 
	endif
endif

# release 4.0
source /usr/local/rsi/idl/bin/idl_setup
setenv IDL_DEVICE X

exit

