#!/bin/csh -f
set HOST_ARCH = `/usr/local/epics/startup/HostArch`

set LOC_PVT=$EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH

if ${?EPICS_EXTENSIONS_PVT} == 1 then
	set LOC_PVT=$EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif

source $LOC_PVT/ezcaidl_setup
source $LOC_PVT/idluserdir_setup
cd $IDL_USERDIR

# source /usr/local/rsi/idl_5/bin/idl_setup

set xdr = "toImage"
if ( "$1" !=  "" ) then
        set xdr = $xdr 
endif

echo ".run toImage" >! go_toImage
echo "$xdr" >>! go_toImage
idl go_toImage
rm go_toImage
