#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
source $EPICS_EXTENSIONS/bin/solaris-sparc/idluserdir_setup
source $PVT_LOC/ezcaidl_setup

set xdr = "toImage"
if ( "$1" !=  "" ) then
        set xdr = $xdr 
endif

# for IDL 5.5 and later -32 option is required for 64 bit
echo ".run toImage" >! go_toImage
echo "$xdr" >>! go_toImage
        source /usr/local/rsi/idl_5.5/bin/idl_setup
        idl -32 go_toImage
rm go_toImage
