#!/bin/csh -f
set HOST_ARCH = `/usr/local/epics/startup/HostArch`
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = $EPICS_EXTENSIONS/bin/$HOST_ARCH

if ${?EPICS_EXTENSIONS_PVT} == 1 then 
	set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif

setenv IDL_DEVICE X

#source /usr/local/rsi/idl_5.1/bin/idl_setup

setenv IDL_STARTUP $PVT_LOC/viewer_startup.pro

set xdr = "dcviewer"
if ( "$1" !=  "" ) then
        set xdr = $xdr',/XDR' 
endif

echo ".run view1d" >! go_viewer
echo ".run view1d_overlay" >>! go_viewer
echo ".run scan2d__define.pro" >>! go_viewer
echo ".run scan1d__define.pro" >>! go_viewer
echo ".run view2d.pro" >>! go_viewer
echo ".run ez_fit" >>! go_viewer
echo ".run dcviewer" >>! go_viewer
echo "$xdr" >>! go_viewer
idl go_viewer
rm go_viewer
