#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
source $EPICS_EXTENSIONS/bin/$EPICS_HOST_ARCH/idluserdir_setup

set xdr = "dcviewer"
if ( "$1" !=  "" ) then
        set xdr = $xdr',/XDR' 
endif

echo ".run view1d" >! go_viewer
echo ".run view1d_overlay" >>! go_viewer
echo ".run scan2d__define.pro" >>! go_viewer
echo ".run scan1d__define.pro" >>! go_viewer
echo ".run view2d.pro" >>! go_viewer
echo ".run ez_fit" >>! go_viewer
echo ".run dcviewer" >>! go_viewer
echo "$xdr" >>! go_viewer
idl go_viewer
rm go_viewer
