#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
source $EPICS_EXTENSIONS/bin/$EPICS_HOST_ARCH/idluserdir_setup

set xdr = "vw2d"

echo ".run panimage" >! go_viewer
echo ".run vw2d" >>! go_viewer
echo ".run assignname_read" >>! go_viewer
echo "assignname_read,dname" >>! go_viewer
echo "$xdr,dname=dname" >>! go_viewer
idl go_viewer
rm go_viewer
