#!/bin/csh -f
#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
set HOST_ARCH = `/usr/local/epics/startup/HostArch`
setenv HOST_ARCH  $HOST_ARCH
set PVT_LOC = $EPICS_EXTENSIONS/bin/$HOST_ARCH

if ${?EPICS_EXTENSIONS_PVT} == 1 then 
	set PVT_LOC = $EPICS_EXTENSIONS_PVT/bin/$HOST_ARCH
endif

#source /usr/local/rsi/idl_5.1/bin/idl_setup
source $PVT_LOC/idluserdir_setup
cd $IDL_USERDIR

setenv IDL_DEVICE X

setenv IDL_STARTUP $PVT_LOC/viewer_startup.pro

set xdr = "vw2d"

echo ".run panimage" >! go_viewer
echo ".run vw2d" >>! go_viewer
echo ".run assignname_read" >>! go_viewer
echo "assignname_read,dname" >>! go_viewer
echo "$xdr,dname=dname" >>! go_viewer
idl go_viewer
rm go_viewer
